FROM openjdk:11

RUN pwd
ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
#ENTRYPOINT ["java","-cp","app:app/lib/*","io.somesh.bose.OrderManagementApplication"]
# -Dspring.cloud.bootstrap.enabled=false , -Dspring.profile.active=local
ENTRYPOINT java -cp app:app/lib/* io.somesh.bose.OrderManagementApplication
